/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.alver.scryfall.api;

import com.alver.fatefall.api.models.scryfall.Set;
import com.alver.scryfall.api.models.ErrorException;
import com.microsoft.rest.ServiceCallback;
import com.microsoft.rest.ServiceFuture;
import com.microsoft.rest.ServiceResponse;
import com.alver.fatefall.api.models.scryfall.SetList;
import rx.Observable;

/**
 * An instance of this class provides access to all the operations defined
 * in Sets.
 */
public interface Sets {
    /**
     *
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @throws ErrorException thrown if the request is rejected by server
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent
     * @return the SetList object if successful.
     */
    SetList getAll();

    /**
     *
     * @param serviceCallback the async ServiceCallback to handle successful and failed responses.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the {@link ServiceFuture} object
     */
    ServiceFuture<SetList> getAllAsync(final ServiceCallback<SetList> serviceCallback);

    /**
     *
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the SetList object
     */
    Observable<SetList> getAllAsync();

    /**
     *
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the SetList object
     */
    Observable<ServiceResponse<SetList>> getAllWithServiceResponseAsync();

    /**
     *
     * @param code the String value
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @throws ErrorException thrown if the request is rejected by server
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent
     * @return the Set object if successful.
     */
    Set getByCode(String code);

    /**
     *
     * @param code the String value
     * @param serviceCallback the async ServiceCallback to handle successful and failed responses.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the {@link ServiceFuture} object
     */
    ServiceFuture<Set> getByCodeAsync(String code, final ServiceCallback<Set> serviceCallback);

    /**
     *
     * @param code the String value
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the Set object
     */
    Observable<Set> getByCodeAsync(String code);

    /**
     *
     * @param code the String value
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the Set object
     */
    Observable<ServiceResponse<Set>> getByCodeWithServiceResponseAsync(String code);

}
