spring.profiles.active: local

#TODO: Hook this up to configuration. Currently hardcoded.
scryfall:
  api:
    url: https://api.scryfall.com

fatefall:
  api:
    server:
      host: http://localhost
      port: 8080
---
spring.config.activate.on-profile: desktop
fatefall:
  api:
    server:
      host: http://192.168.0.111
---
spring.config.activate.on-profile: laptop
fatefall:
  api:
    server:
      host: http://192.168.0.101