spring:
  profiles:
    active: local
  main:
    banner-mode: "off"
    lazy-initialization: true

application:
  title: "Fatefall 0.0 - Custom Card Designer"

scryfall:
  url: https://api.scryfall.com

fatefall:
  url: http://localhost:8080
---
spring.config.activate.on-profile: yohun
fatefall:
  url: http://192.168.0.106:8080
---
spring.config.activate.on-profile: desktop
fatefall:
  url: http://192.168.0.111:8080
---
spring.config.activate.on-profile: laptop
fatefall:
  url: http://192.168.0.101:8080